version: '3.8'

services:
  app:
    build: .
    ports:
      - "5001:3000"  # Map port 5001 of the host to port 3000 of the container
    environment:
      - PORT=5001
      - MONGOURL=${MONGOURL}
      - JWTSECRETKEY=27B5427675142C449CF4B827538EA
      - BASIC_USERNAME=test
      - BASIC_PASSWORD=test
